# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Bundle install
          command: bundle check || bundle install
      - run:
          name: Run tests
          command: |
            mkdir /tmp/test
            bin/rspec --format doc > /tmp/rspec
            cp -R coverage /tmp/coverage
      # collect reports
      - store_artifacts:
          path: /tmp/rspec
          destination: rspec
      - store_artifacts:
          path: /tmp/coverage
          destination: coverage
